# Generated by Django 3.2.10 on 2023-03-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('ex_input', models.TextField(max_length=1000, null=True)),
                ('ex_output', models.TextField(max_length=1000, null=True)),
                ('ex_description', models.TextField(max_length=1000, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Оңай'), (2, 'Орташа'), (3, 'Қиын')], default=1, max_length=128)),
                ('base_code', models.TextField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('testcases_count', models.PositiveSmallIntegerField(default=0)),
                ('time_limit', models.FloatField(default=3, help_text='Time limit in seconds')),
            ],
            options={
                'verbose_name': 'Бағдаламалау Мәселесі',
                'verbose_name_plural': 'Бағдарламалау Мәселелері',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.TextField()),
                ('avg_time', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_memory', models.IntegerField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('success_testcases', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
