# Generated by Django 3.2.10 on 2023-04-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20230410_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': 'Бағдарламалау Сынағы', 'verbose_name_plural': 'Бағдарламалау Сынақтары'},
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(verbose_name='Күтілген нәтиже'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(verbose_name='Кіріс дерегі'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=True, help_text='Кіріс ж-е шығыс деректері қолданушыға көрінбейді', verbose_name='Жабық сынақ?'),
        ),
    ]
