# Generated by Django 4.1.7 on 2023-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('book', 'Book')], default='lesson', max_length=20, null=True),
        ),
    ]
