# Generated by Django 4.1.7 on 2023-02-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0003_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.assignment', verbose_name='Тапсырма атауы'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='files',
            field=models.FileField(upload_to='assignments/', verbose_name='Файлдар'),
        ),
    ]
