# Generated by Django 4.1.7 on 2023-02-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('course', '0006_alter_assignmentsubmission_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='Файлдар'),
        ),
    ]
