# Generated by Django 4.1.7 on 2023-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_assignmentsubmission_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='files',
            field=models.FileField(upload_to='assignment/', verbose_name='Файлдар'),
        ),
    ]
