# Generated by Django 4.1.7 on 2023-02-25 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_assignmentsubmission_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
