# Generated by Django 4.1.6 on 2023-02-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=24)),
                ('link', models.URLField()),
                ('setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_apps', to='website_settings.mainsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=24)),
                ('link', models.URLField()),
                ('setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='website_settings.mainsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='genericimportantpages',
            name='donate_page',
        ),
        migrations.RemoveField(
            model_name='genericimportantpages',
            name='sign_up_page',
        ),
        migrations.DeleteModel(
            name='GenericSocialMediaSettings',
        ),
        migrations.RemoveField(
            model_name='sitespecificimportantpages',
            name='donate_page',
        ),
        migrations.RemoveField(
            model_name='sitespecificimportantpages',
            name='sign_up_page',
        ),
        migrations.RemoveField(
            model_name='sitespecificimportantpages',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitespecificsocialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='GenericImportantPages',
        ),
        migrations.DeleteModel(
            name='SiteSpecificImportantPages',
        ),
        migrations.DeleteModel(
            name='SiteSpecificSocialMediaSettings',
        ),
    ]
