# Generated by Django 4.1.6 on 2023-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0002_mainsettings_mobileapplication_socialmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_play', models.URLField(null=True)),
                ('app_store', models.URLField(null=True)),
                ('app_gallery', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='setting',
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='telegram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='tiktok',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='whatsapp',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='youtube',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='MobileApplication',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
