# Generated by Django 3.2.10 on 2023-05-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20230409_1706'),
        ('leaderboard', '0003_leaderboard_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_of_this_quiz', to='quiz.quiz'),
        ),
    ]
