# Generated by Django 3.2.10 on 2023-05-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20230410_1011'),
        ('quiz', '0006_auto_20230409_1706'),
        ('leaderboard', '0004_auto_20230508_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_of_this_problem', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_of_this_quiz', to='quiz.quiz'),
        ),
    ]
