# Generated by Django 3.2.10 on 2023-04-06 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('visits', models.IntegerField(default=0)),
                ('user_lst', models.TextField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('down_votes', models.ManyToManyField(related_name='down_votes', to=settings.AUTH_USER_MODEL)),
                ('up_votes', models.ManyToManyField(related_name='up_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
