# Generated by Django 3.2.10 on 2023-04-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
