# Generated by Django 3.2.10 on 2023-04-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_discussion_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user_ip',
        ),
    ]
