# Generated by Django 3.2.10 on 2023-04-06 22:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20230407_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
        ),
    ]
