# Generated by Django 3.2.10 on 2023-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_auto_20230407_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default='testst', max_length=255),
            preserve_default=False,
        ),
    ]
