# Generated by Django 3.2.10 on 2023-04-06 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0007_discussion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='down_votes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='reply',
            name='down_votes',
        ),
        migrations.AddField(
            model_name='reply',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='reply',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='reply',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
