# Generated by Django 3.2.10 on 2023-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_auto_20230407_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
