# Generated by Django 3.2.10 on 2023-04-07 02:06

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_discussionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
