# Generated by Django 3.2.10 on 2023-04-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0011_alter_reply_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='description',
            field=models.TextField(),
        ),
    ]
