# Generated by Django 3.2.10 on 2023-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0014_alter_reply_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('answered', 'Жауап берілді'), ('not_answered', 'Жауап берілмеді')], default='not_answered', max_length=20, verbose_name='Күйі'),
        ),
    ]
