# Generated by Django 3.2.10 on 2023-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0002_auto_20230319_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('attempted', 'attempted'), ('attempting', 'Attempting'), ('not', 'NotAttempted')], default='not', max_length=20),
        ),
    ]
