# Generated by Django 3.2.10 on 2023-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0003_attempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('attempted', 'Attempted'), ('attempting', 'Attempting'), ('not', 'NotAttempted')], default='not', max_length=20),
        ),
    ]
