# Generated by Django 3.2.10 on 2023-04-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20230407_0035'),
        ('multiplechoice', '0003_auto_20230407_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name': 'Бірнеше таңдау сұрағы', 'verbose_name_plural': 'Бірнеше таңдау сұрақтары'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.basequestion', verbose_name='Сұрақ'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Реттілікпен'), ('random', 'Рандомды'), ('none', 'Белгісіз')], help_text='Пайдаланушыға Бірнеше таңдауы бар жауап опцияларын көрсету тәртібі', max_length=30, null=True, verbose_name='Жауап тәртібі'),
        ),
    ]
