# Generated by Django 3.2.10 on 2023-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0004_auto_20230319_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptquestion',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
