# Generated by Django 3.2.10 on 2023-03-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('multiplechoice', '0005_auto_20230319_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptquestion',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='correct_answers', to='multiplechoice.Answer'),
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='given_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='given_answers', to='multiplechoice.Answer'),
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.basequestion'),
        ),
    ]
