# Generated by Django 3.2.10 on 2023-03-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0006_auto_20230319_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
