# Generated by Django 3.2.10 on 2023-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], default='', max_length=13),
        ),
    ]
