# Generated by Django 3.2.10 on 2023-05-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20230409_1706'),
        ('assignment', '0010_auto_20230410_0408'),
        ('calendarapp', '0005_auto_20230507_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_events', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_events', to='quiz.quiz'),
        ),
    ]
