# Generated by Django 3.2.10 on 2023-05-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20230508_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
