# Generated by Django 3.2.10 on 2023-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequestion',
            name='correct_answers_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
