# Generated by Django 3.2.10 on 2023-04-06 17:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230328_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Explanation'),
        ),
    ]
