# Generated by Django 3.2.10 on 2023-04-06 18:35

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_basequestion_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='content',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, verbose_name='Сұрақ'),
        ),
        migrations.AlterField(
            model_name='basequestion',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Түсіндірме'),
        ),
        migrations.AlterField(
            model_name='basequestion',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
