# Generated by Django 3.2.10 on 2023-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20230407_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basequestion',
            options={'verbose_name': 'Сұрақ', 'verbose_name_plural': 'Сұрақтар'},
        ),
        migrations.AlterField(
            model_name='basequestion',
            name='content',
            field=models.CharField(help_text='Көрсеткіңіз келетін сұрақтың мәтінін енгізіңіз', max_length=1000, verbose_name='Сұрақ'),
        ),
    ]
