# Generated by Django 3.2.10 on 2023-04-09 11:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20230407_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.Quiz', verbose_name='Бақылау'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Бақылаудың қысқаша сипаттамасы', verbose_name='Сипаттама'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(blank=True, default=False, help_text='Олай болса, тест тесттер тізімінде көрсетілмейді және оны тек тестілерді өңдей алатын пайдаланушылар ғана тапсыра алады.', verbose_name='Уақытша'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Тапсыруға берілетін уақыт', verbose_name='Уақыт'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(verbose_name='Аяқталу уақыты'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(blank=True, help_text='Егер пайдаланушы сәтсіз тапсырса, көрсетілетін мәтін.', verbose_name='Сәтсіз мәтіні'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Әрекеттердің рұқсат етілген саны'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Сәтті тапсыру үшін қажетті пайыз', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Өту балы'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Сұрақтарды кездейсоқ ретпен немесе олар орнатылған ретпен көрсету керек пе?', verbose_name='Рандомды тәртіппен'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(verbose_name='Басталу уақыты'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(blank=True, help_text='Егер пайдаланушы сәтті тапсырса, көрсетілетін мәтін.', verbose_name='Сәтті мәтіні'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Атауы'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='бақылауға сілтеме', max_length=60, verbose_name='Сілтеме'),
        ),
    ]
