# Generated by Django 3.2.10 on 2023-04-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignmentsubmission_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='files',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='comment',
            field=models.TextField(default='', verbose_name='Сипаттама'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.assignment', verbose_name='Тапсырма атауы'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignment.assignmentsubmission', verbose_name='Файлдар')),
            ],
        ),
    ]
