# Generated by Django 3.2.10 on 2023-04-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20230404_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmissionfiles',
            name='file',
            field=models.FileField(null=True, upload_to='assignment/', verbose_name='Файлдар'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionfiles',
            name='assignment_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignment.assignmentsubmission'),
        ),
    ]
