# Generated by Django 3.2.10 on 2023-04-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20230406_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='assignment.assignment', verbose_name='Тапсырма атауы'),
        ),
    ]
