# Generated by Django 3.2.10 on 2023-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_alter_assignmentsubmission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='Баға'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='Бағаланды ма?'),
        ),
    ]
