# Generated by Django 4.1.6 on 2023-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0004_rename_mainsettings_socialmediasettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='slogan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
