# Generated by Django 3.2.10 on 2023-05-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grade', models.PositiveSmallIntegerField(max_length=2)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
